[package]
name = "osp_server_rs"
version = "0.1.0"
authors = ["William Wold <wm@wmww.sh>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
slotmap = "0.4"
anymap = "0.12"
cgmath = "0.17"
serde_json = "1.0"
serde = "1.0"
bimap = "0.4"
ctrlc = "3.1"
mio = "0.6"
webrtc-unreliable = "0.5"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
hyper = { version = "0.13", features = ["stream"] }
