[package]
name = "osp_server_rs"
version = "0.1.0"
authors = ["William Wold <wm@wmww.sh>"]
edition = "2018"

[dependencies]
slotmap = "0.4"
cgmath = "0.17"
serde_json = "1.0"
serde = "1.0"
bimap = "0.4"
mio = "0.6"